# 控制频率
ctrl_rate : 50
# 实飞/仿真 切换，主要确定odom来源
simulation_flag : true
# 记录日志
log_flag : false

# 圆形整定pid
circle_test_flag : false
circle_test_v : 1.0

# constrains
# theta_dot_upper_limit : 1.0
angle_upper_limit : 45.0  # deg

# mpcc
horizon : 25
end_gain_rate : 2.0 # ec, el param rate of end point
w_c : 2.0
w_l : 20.0
gamma : 10.0
w_u : 0.01
w_deltau : 0.001

# reference line
N_SPLINE : 5000

# mpcc valid when dist < 0.3
mpcc_valid_dist : 0.3

# obs penalty and constrains
obs_penalty_valid : false
Qobs : 0.1
obs_x : -1.3
obs_y : -1.1
# obs_x_r : 0.1 # 退化成一个点
# obs_y_r : 0.3
obs_x_r : 0.12 # 退化成一个点
obs_y_r : 0.12

# generate map
generate_pcd_map_flag : true

# dp
enable_dp_flag : false
dp_length_rate : 0.25 # dp_length / 2 * horizon_dist

# z轴高度
hover_height : 1.0
